// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Common;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250416144025_ExampleDateColumn")]
    partial class ExampleDateColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Entities.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExampleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Examples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ÖZEL GÜVENLİK 112. TEMEL EĞİTİM YAZILI SINAV SORULARI (A GRUBU)"
                        });
                });

            modelBuilder.Entity("Entities.Models.GunQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExampleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleId");

                    b.ToTable("GunQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "1. Fişek yatağında fişek bulunan tabancanın güvenli bir şekilde boşaltılması için sırasıyla izlenmesigereken yol nasıl olmalıdır?  \n                    I - Tabanca ölü noktaya çevrilir  \n                    II- Sürgü çekilip gözle fişek yatağı \n                    kontrol edilir ve bırakılır \n                    III- Şarjör çıkartılır \n                    IV- Ölü bölgeye tetik düşürülerek silah \n                    kılıfa konulur ",
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleId = 1,
                            OptionA = "A) I, III, II, IV ",
                            OptionB = "B) III, II, I,IV",
                            OptionC = "C) IV, I,II, III ",
                            OptionD = "D) III, IV, I, II ",
                            OptionE = "E) II, IV, III, I",
                            TrueOption = "A"
                        },
                        new
                        {
                            Id = 2,
                            Content = "2. Aşağıdakilerden hangileri silahın dolduruş yapmasına engel nedenlerden değildir?  \n                I. Şarjörde fişek olmayabilir \n                II. İğne yayı kırık olabilir \n                III. Şarjör tutucu pimi arızalı olabilir \n                IV. Barut miktarı az olabilir  \n                V.  Şarjörde hatalı fişek olabilir.   ",
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleId = 1,
                            OptionA = "A) I-II ",
                            OptionB = "B) I-III-V ",
                            OptionC = "C) II-IV",
                            OptionD = "D) III-IV ",
                            OptionE = "E) I-II-IV",
                            TrueOption = "C"
                        },
                        new
                        {
                            Id = 3,
                            Content = "3. Aşağıdakilerden hangisinde tabancanın sökülme sırası doğru olarak verilmiştir?  \n                I. Kapak takımını çıkart (sürgü) \n                II. Şarjörü çıkart  \n                III. Yerine getiren yayı çıkart \n                IV. Namluyu çıkart \n                V. Fişek yatağını kontrol et ",
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleId = 1,
                            OptionA = "A) II-I-IV-III-V ",
                            OptionB = "B) V-IV-III-II-I ",
                            OptionC = "C) II-V-I-III-IV ",
                            OptionD = "D) III-II-I-V-IV",
                            OptionE = "E) IV-I-V-III-II ",
                            TrueOption = "C"
                        });
                });

            modelBuilder.Entity("Entities.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExampleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrueOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "1. Türkiye’de özel güvenlik anlayışınıntemeli 1981 yılında 2945 sayılı Kanun ileatılmıştır.BuKanunuyürürlüktenkaldıran ve halen yürürlükte olan 5188sayılı Özel Güvenlik Hizmetlerine DairKanun hangi tarihte yürürlüğe girmiştir?",
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleId = 1,
                            OptionA = "A) 2000",
                            OptionB = "B) 2002",
                            OptionC = "C) 2004",
                            OptionD = "D) 2006",
                            OptionE = "E) 2008",
                            TrueOption = "C"
                        },
                        new
                        {
                            Id = 2,
                            Content = "2. 5188sayılı Özel Güvenlik Hizmetlerine Dair   Kanunun   7’inci   maddesinde belirtilen  “Özel  güvenlik  görevlilerinin yetkileri”  ile  ilgili  aşağıdaki  ifadelerden hangisi yanlıştır?",
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleId = 1,
                            OptionA = "A) Terk  edilmiş  ve  bulunmuş  eşyayı emanete alma",
                            OptionB = "B) Olay  yerinde delil  toplama  ve  mağdurun ifadesini alma",
                            OptionC = "C) Tabiî  afet  durumlarında  ve  imdat istenmesi halinde görev alanındaki işyeri ve konutlara girme",
                            OptionD = "D) Görev  alanında,  haklarında  yakalama emri bulunan kişileri yakalama ve arama",
                            OptionE = "E) Kişinin vücudu veya sağlığı bakımından mevcut  bir  tehlikeden  korunması  amacıyla yakalama",
                            TrueOption = "B"
                        },
                        new
                        {
                            Id = 3,
                            Content = "3.Yabancıkişilerin özel güvenlik şirketi kurabilmesi   ve   yabancı   şirketlerin Türkiye’de   özel   güvenlik   hizmeti verebilmesinde aranan temel ilke nedir? ",
                            CreateDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExampleId = 1,
                            OptionA = "A) Mülkilik",
                            OptionB = "B) Şahsilik",
                            OptionC = "C) Koruma",
                            OptionD = "D) Evrensellik",
                            OptionE = "E) Mütekabiliyet",
                            TrueOption = "E"
                        });
                });

            modelBuilder.Entity("Entities.Models.GunQuestion", b =>
                {
                    b.HasOne("Entities.Models.Example", null)
                        .WithMany("GunQuestions")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Question", b =>
                {
                    b.HasOne("Entities.Models.Example", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Example", b =>
                {
                    b.Navigation("GunQuestions");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
